# bunnies forever

In [1]:
## bunnies are lovely

## bunnies are lovely

In [5]:
bunnies

5

In [4]:
bunnies += 1

In [3]:
bunnies=4

In [6]:
def add-nums (x, y, z):

SyntaxError: invalid syntax (<ipython-input-6-61c0c1b84771>, line 1)

In [7]:
def add_nums (x, y, z):
    return x+y+z
print (add_nums(1,2,5))

8


In [8]:
def add_nums (x, y, z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z
    print(add_nums(1,2))
    print(add_nums(1,2,3))


In [9]:
def add_nums (x, y, z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z
print(add_nums(1,2))
print(add_nums(1,2,3))

3
6


In [13]:
def add_nums(x,y,z=None, flag=False):
    if (flag):
        print('flag is true!')
        
    if (z==None):
        return x+y
    else:
        return x+y+z
    
print (add_nums(1,2, flag=True))

flag is true!
3


In [12]:
def add_nums(x,y,z=None, flag=False):
    if (flag):
        print('flag is true!')
        
    if (z==None):
        return x+y
    else:
        return x+y+z
    
print (add_nums(1,2, flag=True))

flag is true!
3


In [1]:
type(add_nums)

NameError: name 'add_nums' is not defined

In [2]:
x=(1, 'a', 2, 'b')
type(x)

tuple

In [3]:
x=[1, 'a', 2, 'b']
type(x)

list

In [4]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


In [5]:
for item in x:
    print(item)

1
a
2
b
3.3


In [6]:
i = 0
while(i != len(x)):
    print (x[i])
    i = i +1

1
a
2
b
3.3


In [7]:
len(x)

5

In [8]:
[1,2] + [3, 4]

[1, 2, 3, 4]

In [9]:
[1] * 3

[1, 1, 1]

In [10]:
1 in [1, 2, 3]

True

In [11]:
4 in [1, 2, 3]

False

In [12]:
x = 'This is a string'
print(x[0])
print(x[0:1])
print(x[0:2])
print (x[5:6])

T
T
Th
i


In [13]:
x[-1]

'g'

In [14]:
x[-2]

'n'

In [15]:
x[-4:-2]

'ri'

In [16]:
x[:3]

'Thi'

In [17]:
x[3:]

's is a string'

In [18]:
x[1]

'h'

In [21]:
firstname = 'Chris'
lastname = 'Brooks'

print(firstname + '    ' + lastname)
print(firstname * 3)
print('Chri' in firstname)

Chris    Brooks
ChrisChrisChris
True


In [22]:
firstname = 'Chris Arthur Hansen Brooks' .split(' ')[0]
lastname = 'Chris Arthur Hansen Brooks' .split(' ')[-1]
print(firstname)
print(lastname)

Chris
Brooks


In [25]:
firstname = 'Chris Arthur Hansen Brooks' .split(' ')
for item in firstname:
    print(item)

Chris
Arthur
Hansen
Brooks


In [28]:
'Chris' + str(2)

'Chris2'

In [31]:
x={'Chris Brooks': 'brooksch@umich.edu', 'Bill Gates':'billg@microsoft.com'}
x['Chris Brooks']

'brooksch@umich.edu'

In [32]:
x['Kevyn Collins'] = None
x['Kevyn Collins']

In [33]:
print(x)

{'Chris Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com', 'Kevyn Collins': None}


In [34]:
for name in x:
    print(x[name])

brooksch@umich.edu
billg@microsoft.com
None


In [35]:
for email in x.values():
    print(email)

brooksch@umich.edu
billg@microsoft.com
None


In [37]:
for name, email in x.items():
    print(name)
    print(email)

Chris Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com
Kevyn Collins
None


In [38]:
x = ('Chris', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x

In [39]:
fname

'Chris'

In [40]:
lname

'Brooks'

In [41]:
email

'brooksch@umich.edu'

In [42]:
sales_record = {'price': 3.24, 
                'num_items': 4, 
                'person': 'Chris'}

sales_statement = '{} bought {}item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                            sales_record['num_items'],
                            sales_record['price'],
                            sales_record['num_items']*sales_record['price']))

Chris bought 4item(s) at a price of 3.24 each for a total of 12.96


In [43]:
sales_record = {'price': 3.24, 
                'num_items': 4, 
                'person': 'Chris'}

sales_statement = '{} bought {}item(s) at a price of {} each for a total of {}'

print(sales_statement)

{} bought {}item(s) at a price of {} each for a total of {}


## Data Files and Summary Statistics

In [3]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [4]:
len(mpg)

234

In [5]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [6]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

In [7]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

23.44

In [2]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))

cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [6]:
CtyMpgCyl = []

for c in cylinders:
    summpg = 0
    cyltypecount = 0
    for d in mpg:
        if d['cyl'] == c:
            summpg += float(d['cty'])
            cyltypecount += 1
    CtyMpgCyl.append((c, summpg / cyltypecount))
    
CtyMpgCyl.sort(key=lambda x: x[0])
CtyMpgCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [7]:
vehicleClass = set(d['class'] for d in mpg)
vehicleClass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [11]:
# Determine the fuel economy of different vehicle classes

HwyMpgByClass = []

for t in vehicleClass: # iterate over all the vehicle classes
    summpg = 0
    vclasscount = 0
    for d in mpg:
        if d['class'] == t:
            summpg += float(d['hwy'])
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, summpg / vclasscount)) # append tuple ('Class', 'avg mpg')
    
HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

In [12]:
# Python Dates and Times

## Get date and time from the time module
import datetime as dt
import time as tm

In [13]:
tm.time()

1488739598.83

In [14]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2017, 3, 5, 12, 48, 53, 31044)

In [15]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second

(2017, 3, 5, 12, 48, 53)

In [16]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second,  dtnow.msec

AttributeError: 'datetime.datetime' object has no attribute 'msec'

In [17]:
delta = dt.timedelta(days = 100)
delta

datetime.timedelta(100)

In [18]:
today = dt.date.today()

In [19]:
today-delta

datetime.date(2016, 11, 25)

In [20]:
today > today-delta

True

In [21]:
class Person:
    dept = 'School of information'
    
    def set_name(self, new_name):
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [24]:
person = Person()
person.set_name('Chris')
person.set_location('MI USA')
print('{} live in {} and works in the dept {}'.format(person.name, person.location, person.dept))

Chris live in MI USA and works in the dept School of information


In [31]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


In [26]:
peeps = ['Dr. Chris Brooks', 'Dr. Kevyn Collins', 'Dr. VG Vinot Vydi', 'Dr. Daniel Romreo'  ]

In [27]:
peeps

['Dr. Chris Brooks',
 'Dr. Kevyn Collins',
 'Dr. VG Vinot Vydi',
 'Dr. Daniel Romreo']

In [30]:
peeps = ['Dr. Chris Brooks', 'Dr. Kevyn Collins', 'Dr. VG Vinot Vydi', 'Dr. Daniel Romreo'  ]
def split_title_and_name(person):
    title = person.split()[0]
    lastname = person.split()[-1]
    return '{} {}'. format(title, lastname)

list(map(split_title_and_name, peeps))

['Dr. Brooks', 'Dr. Collins', 'Dr. Vydi', 'Dr. Romreo']

In [32]:
my_function = lambda a, b, c : a + b

In [33]:
my_function(1, 2, 3)

3

In [35]:
my_function(1,2,3)

3

In [44]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1](person))
          
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))

SyntaxError: invalid syntax (<ipython-input-44-8fa6f5345670>, line 10)

In [ ]:
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)
        
my_list

In [2]:
my_list = [number for number in range(0, 1000) if number % 2 ==0]

In [1]:
my_list = [i*j for i in range(10) for j in range(10)]


In [52]:
# NUMPY
# Creating Arrays
# First step

import numpy as np

In [53]:
# converting a list to an array
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [54]:
# shorter version of above
y = np.array([4,5,6])
y

array([4, 5, 6])

In [55]:
# Creating a two dimensional array
m = np.array([[7,8,9], [10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [56]:
# Determining the matrix shape
m.shape

(2, 3)

In [59]:
# Creating a one row matrix with numbers from 0 to 30 in increments of two
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [60]:
# To convert single row matrix into 2-D of specified size

n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [64]:
# Linspace =|||ar to arange but outputs specified # of elements

o = np.linspace(0,4,9)
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [65]:
# Resize array

o.resize(3,3)
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [66]:
# Create a ? matrix
np.ones((3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [69]:
# Create a Zero matrix
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [70]:
# Create an Identity matrix of specified size
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [71]:
# Create a diagonal matrix with diagonal #s from an array
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [73]:
# Create Repeat matrices, type 1
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [74]:
# Create Repeat matrices, type 2
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [75]:
# Combine arrays: Create one and stack second vertically
p = np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [76]:
# Step 2
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [77]:
# Combine arrays: Create one and stack second horizontally
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [78]:
# matrix operations: Addition
x + y

array([5, 7, 9])

In [79]:
# matrix operations: Multiplication
x * y

array([ 4, 10, 18])

In [80]:
# matrix operations: Raised to a power
x**2

array([1, 4, 9])

In [81]:
# matrix operations: Linear algebra dot product
x.dot(y)

32

In [83]:
# matrix operations: 
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [84]:
z.shape

(2, 3)

In [85]:
# matrix operations: Transpose an array
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [86]:
z.T.shape

(3, 2)

In [87]:
# Determine what type of data an array has using dtype
z.dtype

dtype('int64')

In [88]:
# Chage data type of an array
z = z.astype('f')
z.dtype

dtype('float32')

In [89]:
# Series of Math functions on an array
a = np.array([-4, -2, 1, 3, 5])

In [90]:
a.sum()

3

In [91]:
a.max()

5

In [92]:
a.min()

-4

In [93]:
a.mean()

0.60

In [94]:
a.std()

3.26

In [95]:
# To find the index of a max or min value
a. argmax()

4

In [96]:
a.argmin()

0

In [97]:
# INDEXING AND SLICING
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [98]:
s[0], s[4], s[0:3]

(0, 16, array([0, 1, 4]))

In [99]:
s[1:5]

array([ 1,  4,  9, 16])

In [101]:
s[-4:]

array([ 81, 100, 121, 144])

In [102]:
# Wow! ::
s[-5::-2]

array([64, 36, 16,  4,  0])

In [103]:
# For 2-D arrays
r= np.arange(36) # array of nums 0 to 35
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [104]:
# location of an element
r[2,2]

14

In [105]:
# Get slice of third row and
r[3, 3:6]

array([21, 22, 23])

In [107]:
# first two rows and all columns except last
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [109]:
# Get every second element from the last row
r[-1, :: 2]

array([30, 32, 34])

In [110]:
r[r > 30]

array([31, 32, 33, 34, 35])

In [112]:
# Takes all elements above 30 and replaces them by 30
r[r >30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [113]:
# copying data in numpy. Create an array from r

r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [114]:
# Convert all its elements to zero
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [115]:
# This change transfers to the original array r, so CAREFUL
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [116]:
# Good practice would be to create a copy array to play
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [117]:
# This also shows how to print more than one item
r_copy[:] = 10
print(r_copy)
print()
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


In [120]:
# Iterating through arrays
test = np.random.randint(0, 10, (4,3))
test

array([[8, 3, 8],
       [1, 4, 9],
       [3, 6, 9],
       [7, 3, 4]])

In [121]:
for row in test:
    print(row)

[8 3 8]
[1 4 9]
[3 6 9]
[7 3 4]


In [123]:
for i in range(len(test)):
    print(test[i])

[8 3 8]
[1 4 9]
[3 6 9]
[7 3 4]


In [125]:
for i, row in enumerate(test):
    print('row', i, 'is' ,row)

row 0 is [8 3 8]
row 1 is [1 4 9]
row 2 is [3 6 9]
row 3 is [7 3 4]


In [126]:
test2 = test**2
test2

array([[64,  9, 64],
       [ 1, 16, 81],
       [ 9, 36, 81],
       [49,  9, 16]])

In [127]:
for i, j in zip(test, test2):
    print(i, '+', j, '=', i + j)

[8 3 8] + [64  9 64] = [72 12 72]
[1 4 9] + [ 1 16 81] = [ 2 20 90]
[3 6 9] + [ 9 36 81] = [12 42 90]
[7 3 4] + [49  9 16] = [56 12 20]


In [128]:
['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]

In [131]:
q = np.arange(36)
q.resize(6,6)
q

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [132]:
q[::7]

array([[0, 1, 2, 3, 4, 5]])

In [135]:
q[0:6, ::-7]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [136]:
q[:, ::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [137]:
q.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [138]:
q[2:4, 2:4]

array([[14, 15],
       [20, 21]])